version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
  mlflow:
    image: mlflow/mlflow:latest
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "5000:5000"
